#! /usr/bin/env python

##### Simple script while working on loopllama locally.
#
#
# Usage:
#
#   ./scripts/loopllama serve|kill|open|cmd|help
#
####

from http.server import SimpleHTTPRequestHandler
from os import chdir, getpid
from socketserver import TCPServer
from subprocess import run
from sys import argv
from short_con import cons

APP = 'loopllama'
PORT = 8765
URL = f'http://localhost:{PORT}/{APP}.html'
DIR = f'/Users/mhindman/proj/hindman.github.io/{APP}'
ACTIONS = cons('serve kill open cmd')
USAGE = f'Usage: {APP} ' + '|'.join(ACTIONS.keys())
UTF = 'utf-8'
SERVE_CMD = f'{APP} serve >| /tmp/{APP}.log 2>&1 <&- &'

def main(args):
    action = args[0] if args else None

    if action == ACTIONS.serve:
        chdir(DIR)
        try:
            with TCPServer(('', PORT), SimpleHTTPRequestHandler) as httpd:
                print(f'Serving at {URL}')
                httpd.serve_forever()
        except KeyboardInterrupt:
            print()
            return

    elif action == ACTIONS.kill:
        proc = run(['ps', '-ef'], capture_output = True)
        lines = [
            line
            for line in proc.stdout.decode(UTF).split('\n')
            if APP in line
        ]
        current_pid = getpid()
        pids = [int(line.split()[1]) for line in lines]
        pids = [p for p in pids if p != current_pid]
        if len(pids) == 1:
            run(['kill', str(pids[0])])
        else:
            print('Unable to determine PID. Found these processes:')
            for line in lines:
                print(line)

    elif action == ACTIONS.open:
        run(['open', URL])

    elif action == ACTIONS.cmd:
        print(SERVE_CMD)

    else:
        print(USAGE)
        exit(1)

if __name__ == '__main__':
    main(argv[1:])

